package dev.zymixon.inventory_service.enums;

public enum ItemType {

    COMMON_ITEM_INSTANCE,
    HELMET_ITEM_INSTANCE,
    CHEST_ITEM_INSTANCE,
    ARMOR_ITEM_INSTANCE,
    GLOVES_ITEM_INSTANCE,
    BOOTS_ITEM_INSTANCE,

    WEAPON_ITEM_INSTANCE,
    SWORD_ITEM_INSTANCE,
    AXE_ITEM_INSTANCE,


}
