server:
  port: 8085

spring:
  application:
    name: ENEMY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Connect to Eureka Server
  instance:
    prefer-ip-address: true # Optional, based on your preference
